### PR TITLE
BLANK_SCHEME -> NO_SCHEME, option for custom value

### PR DESCRIPTION
**Pull request by birdsarah**
Also use constant in test.

### CODE REVIEW

**Comment by birdsarah** [comment]
After merging your PR @yabirgb I was about to start using the method and realized I wanted the option to be able to return whatever value I want for no_scheme.

I liked you naming the constant `BLANK_SCHEME`, specifically the `_SCHEME` part, but I realized that I had suggested the use of the word "blank" which seems less clear than just NO, so I tweaked that.

Finally I imported the constant into the test file to test against it rather than hard coding.

Would appreciate your review if you have time.

**Comment by yabirgb** [comment]
Yep, sorry, I forgot to import the constant in the test. The changes seem good and indeed it provides with more flexibility the tool

**Review by yabirgb — APPROVED** [review]

**Review by yabirgb — COMMENTED** [review]
The docstring for no_scheme is missing

**Comment by birdsarah** [comment]
good catch, thanks

**Pull request merged**
